version: '3.8'

services:
  server:
    build:
      context: ./servidor
      dockerfile: Dockerfile
    networks:
      voos_network:
        ipv4_address: 172.16.238.10
    ports:
      - "8082:8082"
    expose:
      - "8082"
    command: python3 server.py

  client1:
    build:
      context: ./cliente
      dockerfile: Dockerfile
    depends_on:
      - server
    networks:
      voos_network:
        ipv4_address: 172.16.238.11
    environment:
      - SERVER_IP=172.16.238.10
    stdin_open: true
    tty: true
    # command: python3 client.py

  test_client:
    build:
      context: ./cliente
      dockerfile: Dockerfile
    depends_on:
      - server
    networks:
      voos_network:
        ipv4_address: 172.16.238.13
    environment:
      - SERVER_IP=172.16.238.10
    command: python3 test_client.py

networks:
  voos_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
