version: '3.8'

services:
  server:
    build:
      context: ./servidor
      dockerfile: Dockerfile
    networks:
      voos_network:
        ipv4_address: 172.16.238.10  # IP fixo para o servidor
    ports:
      - "8082:8082"  # Mapeamento de portas do host para o contêiner
    expose:
      - "8082"  # Expor a porta 8082 para outros serviços na mesma Docker network
    command: python3 server.py

  client1:
    build:
      context: ./cliente
      dockerfile: Dockerfile
    depends_on:
      - server  # Garante que o cliente seja iniciado apenas após o servidor estar ativo
    networks:
      voos_network:
        ipv4_address: 172.16.238.11  # IP fixo para o cliente 1
    environment:
      - SERVER_IP=172.16.238.10  # IP fixo do servidor passado para o cliente
    stdin_open: true  # Permite interação com o cliente
    tty: true

  client2:
    build:
      context: ./cliente
      dockerfile: Dockerfile
    depends_on:
      - server
    networks:
      voos_network:
        ipv4_address: 172.16.238.12  # IP fixo para o cliente 2
    environment:
      - SERVER_IP=172.16.238.10  # IP fixo do servidor passado para o cliente
    stdin_open: true
    tty: true

networks:
  voos_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
