version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "8082:8082"
    networks:
      - voos_network
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8082"]
      interval: 5s
      timeout: 3s
      retries: 5

  client:
    build:
      context: ./client
    networks:
      - voos_network
    stdin_open: true
    tty: true
    environment:
      SERVER_HOST: server
      SERVER_PORT: 8082

networks:
  voos_network:
    driver: bridge
